# Note on matrix inversion

## Inverse

1. The inverse exists if and only if elimination produces n pivots (row exchanges allowed)

2. The matrix A cannot have two different inverses. Suppose $ BA = I $ and also $ AC = I $. Then $ B = C $, according to this "proof by parentheses": $ B(AC) = (BA)C $ gives $ BI = IC $ which is $ B = C $

3. If A is invertible, the one and only solution to $Ax = b$ is $ x = A^{-1}b$
4. **Suppose there is a nonzero vector $x$ such that** $Ax = 0$. Then A _cannot have an inverse_ 
5. A 2 by 2 matrix is invertible if and only if $ad-bc$ is not zero:

$$
{\begin{bmatrix}
a & b\\
c & d
\end{bmatrix}}^{-1} = \frac{1}{ad-bc}
\begin{bmatrix}
d & -b \\
-c & a
\end{bmatrix}
$$

6. A diagonal matrix has an inverse provided no diagonal entries are zero

If $ A = \begin{bmatrix} d_1 & \\ & \ddots & \\ & & d_n \end{bmatrix} $ then $ A^{-1} = \begin{bmatrix} 1/d_1 & \\ & \ddots & \\ & & 1/d_n \end{bmatrix} $

## The Inverses come in reverse order

1. Inverse of $AB$ $(AB)^{-1} = B^{-1}A^{-1}$
2. Invertible = Nonsingular (n pivots)

# The transpose Matrix

## Transpose
1. The **transpose** of $A$ is denoted by $A^T$
2. Entries of $A^T (A^T_{ij} = A_{ji}) $
3. The transpose of $AB$ is $(AB)^T = B^TA^T $
4. The transpose of $A^{-1}$ is $(A^{-1})^T = (A^T)^{-1}$

## Symmetric Metrix

**A symmetric matrix is a matrix that equals its own transpose: $A^T = A$**

# Some calculation example using ipython

In [1]:
%pylab inline
a = array([[1,4],[3,9]])
linalg.inv(a) # inverse of a

Populating the interactive namespace from numpy and matplotlib


array([[-3.        ,  1.33333333],
       [ 1.        , -0.33333333]])

In [21]:
a = 5 * eye(4) - ones((4,4))
print(a)
print(linalg.inv(a))

[[ 4. -1. -1. -1.]
 [-1.  4. -1. -1.]
 [-1. -1.  4. -1.]
 [-1. -1. -1.  4.]]
[[ 0.4  0.2  0.2  0.2]
 [ 0.2  0.4  0.2  0.2]
 [ 0.2  0.2  0.4  0.2]
 [ 0.2  0.2  0.2  0.4]]


# Special matrices and Applications

Large matrices almost always have a clear pattern - frequently a pattern of symmetry, and _very many zero entries_.

Since a sparce matrix contains far fewer than $n^2$ pieces of information, the computations ought to be fast. We look at _band matrices_ to see how concentration near the diagonal speeds up elimination.

**Matrix itself can be seen in equation**
The continuous problem asks for $u(x)$ at every $x$, and a computer cannot solve it exactly. It has to be approximated by a discrete problem -- the more unknowns we keep, the better will be the accuracy and the greater the expense. Our choise falls on the differential equation:

$$ -\frac{d^2u}{dx^2} = f(x), 0 \leq x \leq 1 $$

This is a linear equation for the unknown function $u(x)$. Any combination $C + Dx$ could be added to any solution, since the second derivative of $C + Dx$ contributes nothing. The uncertainty left by these two arbitrary constants C and D is removed by a _"boundary condition"_ at each end of the interval:

$$ u(0) = 0, u(1) = 0 $$

The result is a _two-point boundary-value problem_

We accept a finite amount of information about $f(x)$, say its values at $n$ equally spaced points $x = h, x = 2h, \dots, x = nh$. We compute approximate values $u_1,\dots,u_n$ for the true solution $u$ at these same points. At the ends $x = 0$ and $x = 1 = (n+1)/h$, the boundary values are $u_0 = 0$ and $u_{n+1} = 0$.

The first question: how do we replace the derivative $d^2u/dx^2$? The first derivative can be approximated by stopping at $\Delta u/\Delta x$ at a finite stepsize, and not permitting $h$ (or $\Delta x$) to approach zero. The different $\Delta u$ can be _forward_, _backward_, or _centered_:

\begin{equation} \Delta u/\Delta x = \frac{u(x+h) - u(x)}{h} \end{equation} or \begin{equation} \frac{u(x) - u(x-h)}{h} \end{equation} or \begin{equation} \frac{u(x+h) - u(x-h)}{2h} \end{equation}

The last is symmetric about x and it is the most accurate. For the second derivative there is just one combination that uses only the values at $x$ adn $x\pm h$

**Second difference** $$ \frac{d^2u}{dx^2} \approx \frac{\Delta^2u}{\Delta x^2} = \frac{u(x+h) - 2u(x) + u(x-h)}{h^2} $$

This has the merit of being symmetric about $x$.

**Difference equation** $ -u_{j+1} + 2u_j - u_{j-1} = h^2f(jh) $ for $ j = 1,\dots,n$

The structure of these $n$ equations can be better visualized in matrix form. We choose $h = \frac{1}{6}$, to get a 5 by 5 matrix A:

**Matrix Equation** 

$$
\begin{bmatrix}
2 & -1 & & & \\
-1 & 2 & -1 & & \\
& -1 & 2 & -1 & \\
& & -1 & 2 & -1 \\
& & & -1 & 2 \\
\end{bmatrix} \begin{bmatrix} u_1 \\ u_2 \\ u_3 \\ u_4 \\ u_5 \end{bmatrix} = h^2
\begin{bmatrix}
f(h) \\
f(2h) \\
f(3h) \\
f(4h) \\
f(5h) \\
\end{bmatrix}
$$

The matrix possesses many special properties, and three of those properties are fundamental:

1. **The matrix A is tridiagonal**
All nonzero entries lie on the main diagonal and the two adjacent diagonals. Outside this band all entries are $a_{ij} = 0$. These zeros will bring a tremendous simplification to Gaussian elimination.

$$\begin{bmatrix}
2 & -1 & & & \\
-1 & 2 & -1 & & \\
& -1 & 2 & -1 & \\
& & -1 & 2 & -1 \\
& & & -1 & 2 \\
\end{bmatrix} \rightarrow \begin{bmatrix}
2 & -1 & & & \\
0 & 3/2 & -1 & & \\
& -1 & 2 & -1 & \\
& & -1 & 2 & -1 \\
& & & -1 & 2 \\
\end{bmatrix}$$

2 major simplifications:
* There was only one nonzery entry below the pivot
* The pivot row was very short.

The final result is $LDU = LDL^T$ factorization of A:

$$ A = \begin{bmatrix}1 & & & & \\
-\frac{1}{2} & 1 & & & \\
& -\frac{2}{3} & 1 & & \\
& & -\frac{3}{4} & 1 & \\
& & & -\frac{4}{5} & 1 \\
\end{bmatrix} \begin{bmatrix}
\frac{2}{1} & & & & \\
& \frac{3}{2} & & \\
& & \frac{4}{3} & \\
& & & \frac{5}{4} \\
& & & & \frac{6}{5} \\
\end{bmatrix} 
\begin{bmatrix}
1 & -\frac{1}{2} & & & \\
& 1 & -\frac{2}{3} & \\
& & 1 & -\frac{3}{4} \\
& & & 1 & -\frac{4}{5} \\
& & & & 1 & \\
\end{bmatrix} 
$$

A **band matrix** has $a_{ij} = 0$ except in the band $|i - j| \lt w$

2. **The matrix is symmetric**
Each entry $a_{ij}$ equals its mirror image $a_{ji}$, so that $A^T = A$. The upper triangular $U$ will be the transpose of the lower triangular $L$, and $A = LDL^T$. This symmetry of $A$ reflects the symmetry of $d^2u/dx^2$. An odd derivative like $du/dx$ or $d^3u/dx^3$ would destroy the symmetry.

3. **The matrix is positive definite**
This extra property says that the _pivots are positive_. Row exchanges are unnecessary in theory and in practice.

# Roundoff Error

We expect a roundoff error with each matrix operation. Often we keep a fixed number of significant digits. The adding two number of different size gives an error:

**Roundoff Error**   $ .456 + .00123 \rightarrow .457$

A small pivot forces a practical change in elimination. Normally we compare each pivot with all possible pivots in the same column. Exchanging rows to obtain the largest possible pivot is called **partial pivoting**.

The strategy of _complete pivoting_ looks also in all later columns for the largest possible pivot.

# Least Square

### Projections and Least Squares

It is much better to _choose the x that minimizes an average error E in the m equations_. The most convenient "average" comes from the **Squared error**

**Least squares solution**: 
$$\tilde{x} = \frac{a^Tb}{a^Ta}$$

In general case, we "solve" $ax = b$ by minimizing

$E^2 = ||ax - b||^2 = (a_1x - b_1)^2 + \cdots + (a_mx - b_m)^2$

The derivative of $E^2$ is zero at the point $\hat{x}$, if

$(a_1\hat{x}-b_1)a_1 + \cdots + (a_m\hat{x}-b_m)a_m = 0$

### Least Squares Problems with Several Variables

**to project b onto a subspace** -- rather than just onto a line. This problem arises from $Ax = b$ when $A$ is an $m$ by $n$ matrix.

_Probably, there will not exist a choice of x that perfectly fits the data b_. The problem is to choose $\hat{x}$ so as to minimize the error, and again this minimization will be done in the least-squares sense. The error is $E = ||Ax - b||$, and **this is exactly the distance from $b$ to the point $Ax$ in the column space**. Searching for the least-squares solution $\hat{x}$, which minimizes $E$, is the same as locating the point $p = A\hat{x}$ that is closer to $b$ than any other point in the column space.

**The error vector** $e = b - A\hat{x}$ **must be perpendicular to that space**

Finding $\hat{x}$ and the projection $p = A\hat{x}$ is so fundamental that we do it in two ways:

1. All vectors perpendicular to the column space lie in the left nullspace. Thus the error vector $e = b-A\hat{x}$ must be in the nullspace of $A^T$:
$$A^T(b-A\hat{x}) = 0$$ or $$A^TA\hat{x} = A^Tb$$

2. The error vector must be perpendicular to each column $a_1,\cdots,a_n$ of $A$

When $Ax = b$ is inconsistent, its least-squares solution minimizes $||Ax - b||^2:

**Normal equations** $A^TA\hat{x} = A^Tb$

**Best estimate** $\hat{x} = (A^TA)^{-1}A^Tb$

### Projection Matrices

$P = A(A^TA)^{-1}A^T$

The projection matrix has 2 basic properties:
* It equals its square $P^2 = P$
* It equals its transpose $P^T = P$

### Weighted Least Squares

**Weighted error**: $E^2 = w_1^2(x-b_1)2 + w_2^2(x - b_2)^2$

If $w_1 > w_2$, more importance is attached to $b_1$. The minimizing process (derivative = 0) tries harder to make $(x - b_1)^2$ small:

$\frac{dE^2}{dx} = 2\left[w_1^2(x-b_1) + w_2^2(x-b_2)\right] = 0$ at $\hat{x}_w = \frac{w_1^2b_1 + w_2^2b_2}{w_1^2 + w_2^2}$

**The least squares solution to** $WAx = Wb$ is $\hat{x}_w$:
$A^TW^TWA)\hat{x}_w = A^TW^TWb$