In [1]:
import mxnet as mx
from mxnet import nd

In [ ]:
x = nd.arange(12)
x

In [ ]:
x.shape

In [ ]:
x.size

In [ ]:
x = x.reshape(3,4)
x

In [ ]:
nd.empty((3,4))

In [ ]:
nd.zeros((2,3,4))

In [ ]:
nd.ones((2,3,4))

In [ ]:
x = nd.array([1,2,4,8])
y = nd.ones_like(x) * 2

print('x = ', x)
print('y = ', y)
print('x + y = ', x + y)
print('x * y = ', x * y)
print('x / y = ', x / y)

In [8]:
x = nd.arange(12).reshape((3,4))
y = nd.array([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
print(nd.concat(x,y,dim=0))
print(nd.concat(x,y,dim=1))


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  1.  4.  3.]
 [ 1.  2.  3.  4.]
 [ 4.  3.  2.  1.]]
<NDArray 6x4 @cpu(0)>

[[ 0.  1.  2.  3.  2.  1.  4.  3.]
 [ 4.  5.  6.  7.  1.  2.  3.  4.]
 [ 8.  9. 10. 11.  4.  3.  2.  1.]]
<NDArray 3x8 @cpu(0)>


In [ ]:
x == y

In [7]:
nd.dot(x,y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

In [10]:
x.norm().asscalar()

22.494444

In [11]:
a = nd.arange(3).reshape((3,1))
b = nd.arange(2).reshape((1,2))
print(a,b)
a + b


[[0.]
 [1.]
 [2.]]
<NDArray 3x1 @cpu(0)> 
[[0. 1.]]
<NDArray 1x2 @cpu(0)>



[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

In [20]:
z = y.zeros_like()
print(id(z))
z[:] = x + y
print(id(z))

140202968211296
140202968211296
